### ISSUE TITLE
Error in combo 7112

### ISSUE THREAD

**Issue by MHova** [Commander-Spellbook/commander-spellbook-api-wrapper#12]
[https://CommanderSpellbook.com/?id=7112](url)

Couldn't find another place to submit this.

Iridescent Drake + False Demise + Ashnod's Altar produces infinite mana, not infinite mill. Perhaps that should be Altar of Dementia?

**Comment by crookedneighbor** [comment]
👋  Jump on the discord server mentioned here and post in the submit an update channel: https://github.com/Commander-Spellbook/website-v1#background

The devs (me) on this module don't have access to the raw data to get it updated.

**Comment by crookedneighbor** [comment]
Direct link to Discord: https://discord.gg/DkAyVJG
